# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/kajames/Dropbox/Health Care Insurance/Model2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/kajames/Dropbox/Health Care Insurance/Model2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/kajames/Dropbox/Health Care Insurance/Model2/CMakeFiles" "/home/kajames/Dropbox/Health Care Insurance/Model2/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/kajames/Dropbox/Health Care Insurance/Model2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named healthdp

# Build rule for target.
healthdp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 healthdp
.PHONY : healthdp

# fast build rule for target.
healthdp/fast:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/build
.PHONY : healthdp/fast

health_dp_main.o: health_dp_main.cc.o

.PHONY : health_dp_main.o

# target to build an object file
health_dp_main.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/health_dp_main.cc.o
.PHONY : health_dp_main.cc.o

health_dp_main.i: health_dp_main.cc.i

.PHONY : health_dp_main.i

# target to preprocess a source file
health_dp_main.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/health_dp_main.cc.i
.PHONY : health_dp_main.cc.i

health_dp_main.s: health_dp_main.cc.s

.PHONY : health_dp_main.s

# target to generate assembly for a file
health_dp_main.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/health_dp_main.cc.s
.PHONY : health_dp_main.cc.s

src/dp/decision_cache.o: src/dp/decision_cache.cc.o

.PHONY : src/dp/decision_cache.o

# target to build an object file
src/dp/decision_cache.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/dp/decision_cache.cc.o
.PHONY : src/dp/decision_cache.cc.o

src/dp/decision_cache.i: src/dp/decision_cache.cc.i

.PHONY : src/dp/decision_cache.i

# target to preprocess a source file
src/dp/decision_cache.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/dp/decision_cache.cc.i
.PHONY : src/dp/decision_cache.cc.i

src/dp/decision_cache.s: src/dp/decision_cache.cc.s

.PHONY : src/dp/decision_cache.s

# target to generate assembly for a file
src/dp/decision_cache.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/dp/decision_cache.cc.s
.PHONY : src/dp/decision_cache.cc.s

src/healthcare/configuration/fitness_reader.o: src/healthcare/configuration/fitness_reader.cc.o

.PHONY : src/healthcare/configuration/fitness_reader.o

# target to build an object file
src/healthcare/configuration/fitness_reader.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/fitness_reader.cc.o
.PHONY : src/healthcare/configuration/fitness_reader.cc.o

src/healthcare/configuration/fitness_reader.i: src/healthcare/configuration/fitness_reader.cc.i

.PHONY : src/healthcare/configuration/fitness_reader.i

# target to preprocess a source file
src/healthcare/configuration/fitness_reader.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/fitness_reader.cc.i
.PHONY : src/healthcare/configuration/fitness_reader.cc.i

src/healthcare/configuration/fitness_reader.s: src/healthcare/configuration/fitness_reader.cc.s

.PHONY : src/healthcare/configuration/fitness_reader.s

# target to generate assembly for a file
src/healthcare/configuration/fitness_reader.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/fitness_reader.cc.s
.PHONY : src/healthcare/configuration/fitness_reader.cc.s

src/healthcare/configuration/insurance_reader.o: src/healthcare/configuration/insurance_reader.cc.o

.PHONY : src/healthcare/configuration/insurance_reader.o

# target to build an object file
src/healthcare/configuration/insurance_reader.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/insurance_reader.cc.o
.PHONY : src/healthcare/configuration/insurance_reader.cc.o

src/healthcare/configuration/insurance_reader.i: src/healthcare/configuration/insurance_reader.cc.i

.PHONY : src/healthcare/configuration/insurance_reader.i

# target to preprocess a source file
src/healthcare/configuration/insurance_reader.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/insurance_reader.cc.i
.PHONY : src/healthcare/configuration/insurance_reader.cc.i

src/healthcare/configuration/insurance_reader.s: src/healthcare/configuration/insurance_reader.cc.s

.PHONY : src/healthcare/configuration/insurance_reader.s

# target to generate assembly for a file
src/healthcare/configuration/insurance_reader.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/insurance_reader.cc.s
.PHONY : src/healthcare/configuration/insurance_reader.cc.s

src/healthcare/configuration/job_reader.o: src/healthcare/configuration/job_reader.cc.o

.PHONY : src/healthcare/configuration/job_reader.o

# target to build an object file
src/healthcare/configuration/job_reader.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/job_reader.cc.o
.PHONY : src/healthcare/configuration/job_reader.cc.o

src/healthcare/configuration/job_reader.i: src/healthcare/configuration/job_reader.cc.i

.PHONY : src/healthcare/configuration/job_reader.i

# target to preprocess a source file
src/healthcare/configuration/job_reader.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/job_reader.cc.i
.PHONY : src/healthcare/configuration/job_reader.cc.i

src/healthcare/configuration/job_reader.s: src/healthcare/configuration/job_reader.cc.s

.PHONY : src/healthcare/configuration/job_reader.s

# target to generate assembly for a file
src/healthcare/configuration/job_reader.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/job_reader.cc.s
.PHONY : src/healthcare/configuration/job_reader.cc.s

src/healthcare/configuration/joy_reader.o: src/healthcare/configuration/joy_reader.cc.o

.PHONY : src/healthcare/configuration/joy_reader.o

# target to build an object file
src/healthcare/configuration/joy_reader.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/joy_reader.cc.o
.PHONY : src/healthcare/configuration/joy_reader.cc.o

src/healthcare/configuration/joy_reader.i: src/healthcare/configuration/joy_reader.cc.i

.PHONY : src/healthcare/configuration/joy_reader.i

# target to preprocess a source file
src/healthcare/configuration/joy_reader.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/joy_reader.cc.i
.PHONY : src/healthcare/configuration/joy_reader.cc.i

src/healthcare/configuration/joy_reader.s: src/healthcare/configuration/joy_reader.cc.s

.PHONY : src/healthcare/configuration/joy_reader.s

# target to generate assembly for a file
src/healthcare/configuration/joy_reader.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/joy_reader.cc.s
.PHONY : src/healthcare/configuration/joy_reader.cc.s

src/healthcare/configuration/prob_reader.o: src/healthcare/configuration/prob_reader.cc.o

.PHONY : src/healthcare/configuration/prob_reader.o

# target to build an object file
src/healthcare/configuration/prob_reader.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/prob_reader.cc.o
.PHONY : src/healthcare/configuration/prob_reader.cc.o

src/healthcare/configuration/prob_reader.i: src/healthcare/configuration/prob_reader.cc.i

.PHONY : src/healthcare/configuration/prob_reader.i

# target to preprocess a source file
src/healthcare/configuration/prob_reader.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/prob_reader.cc.i
.PHONY : src/healthcare/configuration/prob_reader.cc.i

src/healthcare/configuration/prob_reader.s: src/healthcare/configuration/prob_reader.cc.s

.PHONY : src/healthcare/configuration/prob_reader.s

# target to generate assembly for a file
src/healthcare/configuration/prob_reader.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/prob_reader.cc.s
.PHONY : src/healthcare/configuration/prob_reader.cc.s

src/healthcare/configuration/reader.o: src/healthcare/configuration/reader.cc.o

.PHONY : src/healthcare/configuration/reader.o

# target to build an object file
src/healthcare/configuration/reader.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/reader.cc.o
.PHONY : src/healthcare/configuration/reader.cc.o

src/healthcare/configuration/reader.i: src/healthcare/configuration/reader.cc.i

.PHONY : src/healthcare/configuration/reader.i

# target to preprocess a source file
src/healthcare/configuration/reader.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/reader.cc.i
.PHONY : src/healthcare/configuration/reader.cc.i

src/healthcare/configuration/reader.s: src/healthcare/configuration/reader.cc.s

.PHONY : src/healthcare/configuration/reader.s

# target to generate assembly for a file
src/healthcare/configuration/reader.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/configuration/reader.cc.s
.PHONY : src/healthcare/configuration/reader.cc.s

src/healthcare/decision.o: src/healthcare/decision.cc.o

.PHONY : src/healthcare/decision.o

# target to build an object file
src/healthcare/decision.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/decision.cc.o
.PHONY : src/healthcare/decision.cc.o

src/healthcare/decision.i: src/healthcare/decision.cc.i

.PHONY : src/healthcare/decision.i

# target to preprocess a source file
src/healthcare/decision.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/decision.cc.i
.PHONY : src/healthcare/decision.cc.i

src/healthcare/decision.s: src/healthcare/decision.cc.s

.PHONY : src/healthcare/decision.s

# target to generate assembly for a file
src/healthcare/decision.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/decision.cc.s
.PHONY : src/healthcare/decision.cc.s

src/healthcare/decision_evaluator.o: src/healthcare/decision_evaluator.cc.o

.PHONY : src/healthcare/decision_evaluator.o

# target to build an object file
src/healthcare/decision_evaluator.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/decision_evaluator.cc.o
.PHONY : src/healthcare/decision_evaluator.cc.o

src/healthcare/decision_evaluator.i: src/healthcare/decision_evaluator.cc.i

.PHONY : src/healthcare/decision_evaluator.i

# target to preprocess a source file
src/healthcare/decision_evaluator.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/decision_evaluator.cc.i
.PHONY : src/healthcare/decision_evaluator.cc.i

src/healthcare/decision_evaluator.s: src/healthcare/decision_evaluator.cc.s

.PHONY : src/healthcare/decision_evaluator.s

# target to generate assembly for a file
src/healthcare/decision_evaluator.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/decision_evaluator.cc.s
.PHONY : src/healthcare/decision_evaluator.cc.s

src/healthcare/enjoyment/fractional.o: src/healthcare/enjoyment/fractional.cc.o

.PHONY : src/healthcare/enjoyment/fractional.o

# target to build an object file
src/healthcare/enjoyment/fractional.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/enjoyment/fractional.cc.o
.PHONY : src/healthcare/enjoyment/fractional.cc.o

src/healthcare/enjoyment/fractional.i: src/healthcare/enjoyment/fractional.cc.i

.PHONY : src/healthcare/enjoyment/fractional.i

# target to preprocess a source file
src/healthcare/enjoyment/fractional.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/enjoyment/fractional.cc.i
.PHONY : src/healthcare/enjoyment/fractional.cc.i

src/healthcare/enjoyment/fractional.s: src/healthcare/enjoyment/fractional.cc.s

.PHONY : src/healthcare/enjoyment/fractional.s

# target to generate assembly for a file
src/healthcare/enjoyment/fractional.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/enjoyment/fractional.cc.s
.PHONY : src/healthcare/enjoyment/fractional.cc.s

src/healthcare/fitness/composite.o: src/healthcare/fitness/composite.cc.o

.PHONY : src/healthcare/fitness/composite.o

# target to build an object file
src/healthcare/fitness/composite.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/fitness/composite.cc.o
.PHONY : src/healthcare/fitness/composite.cc.o

src/healthcare/fitness/composite.i: src/healthcare/fitness/composite.cc.i

.PHONY : src/healthcare/fitness/composite.i

# target to preprocess a source file
src/healthcare/fitness/composite.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/fitness/composite.cc.i
.PHONY : src/healthcare/fitness/composite.cc.i

src/healthcare/fitness/composite.s: src/healthcare/fitness/composite.cc.s

.PHONY : src/healthcare/fitness/composite.s

# target to generate assembly for a file
src/healthcare/fitness/composite.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/fitness/composite.cc.s
.PHONY : src/healthcare/fitness/composite.cc.s

src/healthcare/fitness/fixed_price.o: src/healthcare/fitness/fixed_price.cc.o

.PHONY : src/healthcare/fitness/fixed_price.o

# target to build an object file
src/healthcare/fitness/fixed_price.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/fitness/fixed_price.cc.o
.PHONY : src/healthcare/fitness/fixed_price.cc.o

src/healthcare/fitness/fixed_price.i: src/healthcare/fitness/fixed_price.cc.i

.PHONY : src/healthcare/fitness/fixed_price.i

# target to preprocess a source file
src/healthcare/fitness/fixed_price.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/fitness/fixed_price.cc.i
.PHONY : src/healthcare/fitness/fixed_price.cc.i

src/healthcare/fitness/fixed_price.s: src/healthcare/fitness/fixed_price.cc.s

.PHONY : src/healthcare/fitness/fixed_price.s

# target to generate assembly for a file
src/healthcare/fitness/fixed_price.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/fitness/fixed_price.cc.s
.PHONY : src/healthcare/fitness/fixed_price.cc.s

src/healthcare/period_result.o: src/healthcare/period_result.cc.o

.PHONY : src/healthcare/period_result.o

# target to build an object file
src/healthcare/period_result.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/period_result.cc.o
.PHONY : src/healthcare/period_result.cc.o

src/healthcare/period_result.i: src/healthcare/period_result.cc.i

.PHONY : src/healthcare/period_result.i

# target to preprocess a source file
src/healthcare/period_result.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/period_result.cc.i
.PHONY : src/healthcare/period_result.cc.i

src/healthcare/period_result.s: src/healthcare/period_result.cc.s

.PHONY : src/healthcare/period_result.s

# target to generate assembly for a file
src/healthcare/period_result.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/period_result.cc.s
.PHONY : src/healthcare/period_result.cc.s

src/healthcare/person.o: src/healthcare/person.cc.o

.PHONY : src/healthcare/person.o

# target to build an object file
src/healthcare/person.cc.o:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/person.cc.o
.PHONY : src/healthcare/person.cc.o

src/healthcare/person.i: src/healthcare/person.cc.i

.PHONY : src/healthcare/person.i

# target to preprocess a source file
src/healthcare/person.cc.i:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/person.cc.i
.PHONY : src/healthcare/person.cc.i

src/healthcare/person.s: src/healthcare/person.cc.s

.PHONY : src/healthcare/person.s

# target to generate assembly for a file
src/healthcare/person.cc.s:
	$(MAKE) -f CMakeFiles/healthdp.dir/build.make CMakeFiles/healthdp.dir/src/healthcare/person.cc.s
.PHONY : src/healthcare/person.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... healthdp"
	@echo "... edit_cache"
	@echo "... health_dp_main.o"
	@echo "... health_dp_main.i"
	@echo "... health_dp_main.s"
	@echo "... src/dp/decision_cache.o"
	@echo "... src/dp/decision_cache.i"
	@echo "... src/dp/decision_cache.s"
	@echo "... src/healthcare/configuration/fitness_reader.o"
	@echo "... src/healthcare/configuration/fitness_reader.i"
	@echo "... src/healthcare/configuration/fitness_reader.s"
	@echo "... src/healthcare/configuration/insurance_reader.o"
	@echo "... src/healthcare/configuration/insurance_reader.i"
	@echo "... src/healthcare/configuration/insurance_reader.s"
	@echo "... src/healthcare/configuration/job_reader.o"
	@echo "... src/healthcare/configuration/job_reader.i"
	@echo "... src/healthcare/configuration/job_reader.s"
	@echo "... src/healthcare/configuration/joy_reader.o"
	@echo "... src/healthcare/configuration/joy_reader.i"
	@echo "... src/healthcare/configuration/joy_reader.s"
	@echo "... src/healthcare/configuration/prob_reader.o"
	@echo "... src/healthcare/configuration/prob_reader.i"
	@echo "... src/healthcare/configuration/prob_reader.s"
	@echo "... src/healthcare/configuration/reader.o"
	@echo "... src/healthcare/configuration/reader.i"
	@echo "... src/healthcare/configuration/reader.s"
	@echo "... src/healthcare/decision.o"
	@echo "... src/healthcare/decision.i"
	@echo "... src/healthcare/decision.s"
	@echo "... src/healthcare/decision_evaluator.o"
	@echo "... src/healthcare/decision_evaluator.i"
	@echo "... src/healthcare/decision_evaluator.s"
	@echo "... src/healthcare/enjoyment/fractional.o"
	@echo "... src/healthcare/enjoyment/fractional.i"
	@echo "... src/healthcare/enjoyment/fractional.s"
	@echo "... src/healthcare/fitness/composite.o"
	@echo "... src/healthcare/fitness/composite.i"
	@echo "... src/healthcare/fitness/composite.s"
	@echo "... src/healthcare/fitness/fixed_price.o"
	@echo "... src/healthcare/fitness/fixed_price.i"
	@echo "... src/healthcare/fitness/fixed_price.s"
	@echo "... src/healthcare/period_result.o"
	@echo "... src/healthcare/period_result.i"
	@echo "... src/healthcare/period_result.s"
	@echo "... src/healthcare/person.o"
	@echo "... src/healthcare/person.i"
	@echo "... src/healthcare/person.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
